name: Build and Push Frontend Image to ACR

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get next version
              uses: reecetech/version-increment@2024.4.3
              id: version
              with:
                scheme: semver
                increment: patch

            - name: Azure Login
              uses: Azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: checkout cicd
              uses: actions/checkout@v2
              with:
                repository: 'Suah-Cho/CICD-pipeline'
                ref: main
                token: ${{ secrets.PAT }}
                path: CICD-pipeline
              
            - name: make env file
              run: |
                ls -al
                cd CICD-pipeline/resources/scripts
                chmod +x make_env.bash
                ./make_env.bash dev
                ls -al

            - name: Image build and testing
              run: |
                docker buildx build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ steps.version.outputs.version }} .
                docker run -d -p 8080:8000 --name test ${{ secrets.ACR_LOGIN_SERVER}}/backend:${{ steps.version.outputs.version }}

                echo "Waiting for the container to start..."

                sleep 2
                docker ps
                
                echo "Testing /api/docs/endpoint..."
                status_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/api/docs)
                echo "Received status code: $status_code"


