name: Build and Push Frontend Image to ACR

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Azure Login
              uses: Azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
              
            - name: Get secrets
              uses: Azure/get-keyvault-secrets@v1
              with:
                keyvault: "croft-gp-kv"
                secrets: "GP-DEV-API-MODE"
              