name: Build and Push Frontend Image to ACR

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Get secrets
              uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
              with:
                login_credentials: ${{ secrets.AZURE_CREDENTIALS }}
                keyvault: croft-gp-kv
                secrets_file_path: ./secrets.env
              
            - name: test confirm
              run: |
                cat ./secrets.env
            