name: Build and Push Frontend Image to ACR

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Azure Login
              uses: Azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: checkout cicd
              uses: actions/checkout@v2
              with:
                repository: 'Suah-Cho/CICD-pipeline'
                ref: main
                token: ${{ secrets.PAT }}
                path: CICD-pipeline
              
            - name: make env file
              run: |
                cd CICD-pipeline/resources/script
                ./make_env.bash dev

            - name: Confirm
              run: |
                cat ./dev.env
              